url: http://dev.solita.fi
title: /dev/solita
description: Solita developer blog
gems: [jekyll-paginate]
paginate: 10
paginate_path: "/:num"
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM


authors:
  jarno:
    name: Jarno Peltoniemi
    email: 30bad10249ad7938521a26ea1cafcd8a
    url: http://www.solita.fi
  ajk:
    name: Antti-Jussi Kovalainen
    email: 5ff6a8a0ce50e9de363cb9a00b1cc804
    url: http://ajk.fi/
  massimo:
    name: Massimo Prencipe
    email: 1d369f0b94f9ed31c2e84cbbceea00e1
    url: http://www.solita.fi
  lokori:
    name: Antti Virtanen
    email: a364d662d46eafc7684fda3c71278194
    url: http://www.solita.fi
  n1ko:
    name: Niko Kurtti
    email: e8c38258967f00e2a4a5b87a97ae135b
    url: http://www.solita.fi
  timole:
    name: Timo Lehtonen
    email: 5df17e991440842ef6b55570d5b61f90
    url: http://www.solita.fi
  empperi:
    name: Niklas Collin
    email: a046826c81ce53c8544d2e00e6033312
    url: http://blogs.collin.fi/npe/
  orfjackal:
    name: Esko Luontola
    email: a2bbd6c20c20edf4620cb8c6379aacc8
    url: http://www.orfjackal.net/
  harmia:
    name: Juhana Harmanen
    email: e1917d35d762436f76ca18eaa6018f37
    url: http://www.solita.fi
  noidi:
    name: Timo Mihaljov
    email: f3cc3f114c258a4f25e02c4b62fae433
    url: https://twitter.com/noidi
  ruoat:
    name: Ari Ruotsalainen
    email: f9d260198adcd6324956e91f328bd318
    url: https://twitter.com/ruotsalaisenari
  aautio:
    name: Ari Autio
    email: 7a2f51f46a11d56fb6f8581af89521b6
    url: https://twitter.com/ariautio
  pvto:
    name: Paavo Toivanen
    email: 3cfeb0502e2fd169e08348f77bb01a1d
    url: http://www.solita.fi
  arto:
    name: Arto Santala
    email: dc3bf4adfabce83f904b9563f927641d
    url: https://spagettikoodi.wordpress.com/
  juuso:
    name: Juuso Hyvönen
    email: 8a528aee07705cfc166b57564e242db6
    url: http://www.solita.fi
  tatut:
    name: Tatu Tarvainen
    email: 6a2a988e9cff23f52444914d14bd0a96
    url: http://www.solita.fi
  jessek:
    name: Jesse Korpela
    email: ee6747c4fa0cd979a9995299e215feb4
    url: http://www.solita.fi
  jarzka:
    name: Jari Hanhela
    email: 429ac35a7d794684181d64a5befd040c
    url: http://www.voimala.org
  jerekapyaho:
    name: Jere Käpyaho
    email: 4ef76183965fe0d12de8dcdab512ca3a
    url: http://www.coniferproductions.com
  Rinorragi:
    name: Joona Immonen
    email: 2cb033c2473824d802cca09001da9025
    url: https://www.linkedin.com/in/joonaimmonen
  riipah:
    name: Jukka Hyvärinen
    email: fa431c5a37bbdde5c47570432789b73a
    url: http://www.solita.fi/
  bafe:
    name: Pauli Kärpänoja
    email: 339b324c15d0c88ebfbda2ca6ef677f7
    url: https://twitter.com/karpanoja
  pkalliok:
    name: Panu Kalliokoski
    email: e7a94f01372caecec47d6fd9b3f31f60
    url: https://fi.linkedin.com/in/panu-kalliokoski-821768b2
  dratini:
    name: Jouni Huttunen
    email: ea79677c8e7395e138a46fa304109957
    url: https://www.linkedin.com/in/dratini
  timovi:
    name: Timo Viisteensaari
    email: dd91a146d068fb2c15bb275e17fc568d
    url: https://www.linkedin.com/in/timo-viisteensaari-1780596
  Kauko:
    name: Teemu Kaukoranta
    email: d0f83e2b711ccaa7468cf6b0b11900e8
    url: https://twitter.com/TeemuKaukoranta
  riikkanen:
    name: Riikka Taiminen
    email: 9ce425a78928e0c957510acd215ea1b3
    url: http://www.solita.fi/
  juhofriman:
    name: Juho Friman
    email: 08441148498196c219300f1726632923
    url: http://www.twitter.com/commafakir
  HannuToi:
    name: Hannu Toivola
    email: 5e0d013c6e98920c51091f5958bc4a1a
    url: http://www.solita.fi/
  viesti:
    name: Kimmo Koskinen
    email: 68fe78dff2b49d1ae0184a5c321cc3f8
    url: http://www.solita.fi/
  fingerzam:
    name: Juhana Laurinharju
    email: 30622a7698cec913d62eac996cfcb4ca
    url: http://www.solita.fi/
  ilmoraunio:
    name: Ilmo Raunio
    email: c0201865365e35abb07057e909a67404
    url: https://www.linkedin.com/in/ilmo-raunio-b982b031
  jesperin:
    name: Jesper Ingström
    email: 3916c482cb5d11ab5ec5526f44861026
    url: https://www.linkedin.com/in/jesper-ingstrom
  ollimkn:
    name: Olli Mäkinen
    email: d6d50ad6d2224495e492895bd0b6d646
    url: https://www.linkedin.com/in/ollimkn
  jarnovayrynen:
    name: Jarno Väyrynen
    email: 803d2fa78db5d2fdde87e0b2fb9d61b0
    url: https://www.linkedin.com/in/jarnovayrynen/
  mikkoronkkomaki:
    name: Mikko Rönkkömäki
    email: a63a77db92a86ba8b7be27ce6ed1cf72
    url: https://www.linkedin.com/in/mikkoronkkomaki/
  tommiraunio:
    name: Tommi Raunio
    email: 23ae2bc8e203be2f8482edfb1efeeadb
    url: https://www.linkedin.com/in/tommi-raunio-a3393138/ 
