title: Solita Dev
authors:
  jarno:
    name: Jarno Peltoniemi
    url: mailto:jarno.peltoniemi@solita.fi
  ajk:
    name: Antti-Jussi Kovalainen
    url: http://ajk.im
    email: antti-jussi.kovalainen@solita.fi

