url: http://dev.solita.fi
title: /dev/solita
description: Solita developer blog
pygments: true
authors:
  jarno:
    name: Jarno Peltoniemi
    email: jarno.peltoniemi@solita.fi
    url: mailto:jarno.peltoniemi@solita.fi
  ajk:
    name: Antti-Jussi Kovalainen
    email: ajk@solita.fi
    url: http://ajk.fi/
  massimo:
    name: Massimo Prencipe
    email: massimo.prencipe@solita.fi
    url: mailto:massimo.prencipe@solita.fi
  lokori:
    name: Antti Virtanen
    email: antti.virtanen@solita.fi
    url: mailto:antti.virtanen@solita.fi
  n1ko:
    name: Niko Kurtti
    email: niko.kurtti@solita.fi
    url: mailto:niko.kurtti@solita.fi
  timole:
    name: Timo Lehtonen
    email: timo.lehtonen@solita.fi
    url: mailto:timo.lehtonen@solita.fi
  empperi:
    name: Niklas Collin
    email: niklas.collin@solita.fi
    url: http://blogs.collin.fi/npe/
  orfjackal:
    name: Esko Luontola
    email: esko.luontola@solita.fi
    url: http://www.orfjackal.net/
  harmia:
    name: Juhana Harmanen
    email: juhana.harmanen@solita.fi
    url: mailto:juhana.harmanen@solita.fi
  noidi:
    name: Timo Mihaljov
    email: timo.mihaljov@solita.fi
    url: https://twitter.com/noidi
  ruoat:
    name: Ari Ruotsalainen
    email: ari.ruotsalainen@solita.fi
    url: mailto:ari.ruotsalainen@solita.fi
