title: /dev/solita
description: Solita developer blog
authors:
  jarno:
    name: Jarno Peltoniemi
    email: jarno.peltoniemi@solita.fi
    url: mailto:jarno.peltoniemi@solita.fi
  ajk:
    name: Antti-Jussi Kovalainen
    email: ajk@solita.fi
    url: http://ajk.fi/
  massimo:
    name: Massimo Prencipe
    email: massimo.prencipe@solita.fi
    url: mailto:massimo.prencipe@solita.fi
  lokori:
    name: Antti Virtanen
    email: antti.virtanen@solita.fi
    url: mailto:antti.virtanen@solita.fi
  n1ko:
    name: Niko Kurtti
    email: niko.kurtti@solita.fi
    url: mailto:niko.kurtti@solita.fi
  timole:
    name: Timo Lehtonen
    email: timo.lehtonen@solita.fi
    url: mailto:timo.lehtonen@solita.fi
  empperi:
    name: Niklas Collin
    email: niklas.collin@solita.fi
    url: http://blogs.collin.fi/npe/